name: "Run static analysis for C++ project"
description: "Runs cppcheck and clang-tidy on CMake based project. The result will be added as PR comment"

inputs:
  github_token:
    description: 'Github token used for Github API requests'
    required: true
    default: ${{ github.token }}
  pr_num:
    description: 'Pull request number'
    default: ${{ github.event.pull_request.number }}
    required: true
  repo:
    description: 'Repository name'
    default: ${{ github.repository }}
    required: true
  comment_title:
    description: 'Unique title for comment'
    default: Static analysis result
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book-open"
  color: "white"
